### ISSUE TITLE
Testing with pamqp 3.0.0a4

### ISSUE THREAD

**Issue by gmr** [fake-name/AutoTriever#525]
I plan on releasing pamqp 3.0 soon and wanted to make sure you were aware of the changes that are making it into 3.0 and give you an opportunity to report any issues prior to its release.

Please see the version history @ https://pamqp.readthedocs.io/en/latest/history.html

**Comment by gmr** [comment]
Closing as I see you are using pamqp by way of rabbitpy.

**Comment by fake-name** [comment]
The RPC client end uses rabbitpy.

The server end uses a [vendored version of amqpstorm](https://github.com/fake-name/ReadableWebProxy/tree/master/amqpstorm), mostly because it was easiest to hack thread-killing into it. It's been reasonably robust after the changes I made (e.g. I've not been able to get the thread that runs the AMQP comms to wedge forever).
